#!/bin/sh

set -e

function err() {
  echo "[ERROR] $1" >&2
  exit 1
}

function smitty() {
  echo; echo
  echo "[INFO] $@"
  $@
}

git remote show upstream &> /dev/null || smitty git remote add upstream https://github.com/jumanjiman/wormhole.git

rm -f Gemfile.lock
smitty bundle update 2> /dev/null || smitty bundle install --path=~/.bundle
