#!/usr/bin/env bash

set -e

echo "===> Bundling..."
script/bootstrap

echo "===> Building image..."
pushd wormhole 2> /dev/null
docker build --rm -t jumanjiman/wormhole .
popd 2> /dev/null

echo "===> Running rspec"
bundle exec rake rubocop
bundle exec rake spec
